### ISSUE TITLE
Mängija vaates kaardil klikates avaneb küsimus

### ISSUE THREAD

**Issue by tammets** [Avastusrada/Avastusrada#1]
Asukohad (_pins_) on mängija vaates kaardil klikatavad ning annavad teate kas liiga kaugest punktist või avavad küsimuse/ülesande/info.

**Comment by JTerasmaa** [comment]
kasutajate tagasisidest on tulnud ka mõte, et võikski korraga näha olla ainult nö aktiivne küsimus või selle pealkiri. Hetkel see nimekiri võtab liiga palju ekraaniruumi ära. Saaks kaarti suuremalt kuvada. Või siis saab nimekirja nö sisse ja välja lülitada või kuhugi serva taha ära saata, et ei peaks viimaste rajapunktide läbimisel edasi-tagasi skrollima.

Teine variant on, et juba vastatud küsimused kaovad nimekirjast ära. Miks mitte ka koos läbitud rajapunktidega kaardilt.
