### ISSUE TITLE
Mängutulemuste saatmine osalejale meilile peale mängu lõppemist

### ISSUE THREAD

**Issue by tammets** [Avastusrada/Avastusrada#16]
Mängu lõpetanule saadetakse mängule registreerumiseks kasutatud e-mailile õiged vastused (/kuvatakse pärast raja läbimist õigeid vastuseid otse veebilehitsejas). Seda, millise raja puhul see toimub ja millise puhul mitte, saab määrata raja loojal.

**Comment by JTerasmaa** [comment]
Testisin seda. Meiliga vist peaks kaasas olema ka raja kaart, aga seda ei kuvata, link vist katki.

Lisaks äkki vaikimisi peaks see olema väljalülitatud? Äkki kõik ei taha, et kiri mängijale läheks. Aga võibolla pole see ka probleemiks.

Tegelikult pani see nüüd mõte liikuma ühe täienduse osas. Aga see pigem tuleviku jaoks. Kui muidugi väga lihtsalt lahendatav pole?

Nimelt peaks vastustega kaasas olema ka küsimus. Aga paraku on need sageli üsna pikad tekstid.  Seega peaks küsimuse sisestamisel tekitama kaks lahtrit - selgitav tekst ja konkreetne küsimus (juhul kui see on). Kui küsimust ei ole, siis ongi infopunkt. Selliselt saaks äkki küsimuse sisestamise isegi lihtsamaks teha, üks valik ju vähem - punkti stiil sõltub sellest, kas täidad ühe või kaks lahtrit ehket kas tahad vastust või mitte.

Ning tegelikult oleks vaja veel ka kolmandat lahtrit - õige vastust. Valikvastustega küsimuste korral on õige vastus emailis kenasti olemas, aga vaba vastuse korral mitte. Järelikult peaks olema võimalik raja sisestajal soovikorral eelnevalt sisestada ka vastused või kommentaarid, ning need läheks kirjaga kaasa. Aga see oleks rohkem selline "optional" funktsioon ma arvan. Samas just sellist tagasisidet on osad mängijad oodanud - et teada saada kas nad vastasid õigesti või mitte. Oleks ka pedagoogiliselt hea.

**Comment by JTerasmaa** [comment]
Ja sama asjaga haakuv - kui juba, siis küsimus võiks olemas olla ka eksporditavas CSV failis.

Ja noh paraku CSV on asi, mis kõikides ikkagi küsimusi ja probleeme tekitab. Äkki ods oleks parem? Seda oskavad vist ju kõik erinevad platvormid avada.

**Comment by tammets** [comment]
- Kaarti kuvatakse kui pildid on kirjas lubatud (sõltub teenusepakkujast ja e-posti kliendist)
- Tulemuste saatmine on valikuline võimalus
- Õige vastus on eraldi märgitud
- Küsimused on kirjas samuti sees
- CSV faili küsimuse jätab hetkel töödest välja kuid loob uue pileti arutamiseks
