### ISSUE TITLE
Mängu registreerumisel Error 500

### ISSUE THREAD

**Issue by JTerasmaa** [Avastusrada/Avastusrada#25]
Ilmselt viga meiliserveris?

Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by tammets** [comment]
Tere!

Nägin ka hommikul, uurime juba,
Tänud

**Comment by JTerasmaa** [comment]
Nüüd seda errorit enam ei ole, aga email ikkagi kohale ei tule?
