### ISSUE TITLE
Küsimuste juures olevad pildid on kadunud

### ISSUE THREAD

**Issue by JTerasmaa** [Avastusrada/Avastusrada#28]
#Selgus selline asi, et lingid küsimuste juures olevatele piltidele on vigased.

Painstab olevat keele lisandumisel tekkinud probleem. Pildid on olemas aadressil 

> https://avastusrada.ee/uploads/...

Aga vastavalt valitud keelest viib küsimuse juures olev katkine pildilink aadressile

> https://avastusrada.ee/et/uploads/...

Ilmselt peab piltide linkimise muutma keelest sõltumatuks.

**Comment by JTerasmaa** [comment]
See konkreetne probleem sai kenasti lahenduse. Aga paraku uusi pilte ei saa ka lisada. Valid faili ära, aga vajutades "salvesta" ei juhtu midagi. 

Äkki samuti salvestuskataloogi asukohaga seotud viga?

**Comment by tammets** [comment]
Pilet #29
