### ISSUE TITLE
Keele valik

### ISSUE THREAD

**Issue by JTerasmaa** [Avastusrada/Avastusrada#34]
Kasutajal on võimalik vahetada keskkonna kasutajaliidese keelt ülaservas olevast rippmenüüst. Vaikimisi keskkonna keel on alati eesti keel.

![screen shot 2017-03-23 at 10 42 14](https://cloud.githubusercontent.com/assets/380007/24240055/021e3ada-0fb9-11e7-94da-88b971a7795f.png)

**Comment by tammets** [comment]
Keelevalik on hetkel viidud jalusesse tulenevalt uuest disainist, mida ühel hetkel implementeeritakse.
