### ISSUE TITLE
Läbitud punktid (markerid) kuvada kaardil teist tooni / värvi

### ISSUE THREAD

**Issue by tammets** [Avastusrada/Avastusrada#4]

**Comment by JTerasmaa** [comment]
Juba vastatud küsimused võiks ka nimekirjast ära kaduda, et lõpupoole ei peaks kaardi nägemiseks üles-alla kerima. Aktiivne küsimus või järgmine punkt on selliselt alati esimene.

**Comment by tammets** [comment]
Teeksin pigem ettepaneku vastamata küsimused kuvada nimekirjas allpool ning vastatud üleval. Küsimus peaks avanema mh ka markeril klikates kuid järgmist punkti ei ole alati võimalik eespool kuvada, sest raja läbimine ei pruugi eeldada lineaarset läbimist.

**Comment by JTerasmaa** [comment]
See eeldaks jah tihedamat sidet kaardil oleva punkti ja küsimuse vahel. Markeril vajutades küsimuse avanemine oleks väga hea (Y).

Oot aga kas ajasid "allpool" ja "ülevalpool" sassi? ikka vastamata küsimused peaks ju ülevalpool olema ja vastatud kuhugi alla ära kolima? Või siis ikkagi üldse ära kaduma. Muidu peaks ju nimekiri jooksvalt ümbersorteeruma, nii et lähim on alati esimene? Või kuidas sa täpselt seda mõtled.

Tegelikult see on jube oluline kasutusmugavuse ja funktsionaalsuse küsimus ja peab jube täpselt läbi arutama, et hiljem jälle ringi ei peaks tegema :-)

Sest kui me eeldame, et punkte ei pea lineaarselt läbima, siis nüüd lisandunud numbrid ju tekitatavad selle mulje ikkagi üsna tugevalt, et pean nende järjekorras liikuma, isegi kui nüüd markereid ühendav joon ära korjata.

**Comment by tammets** [comment]
Ajasin sassi, tõsi.

Ja on õigus, et punktid peaksid olema nummerdatud. St sinu mõttekäik eespool õige. Korrigeerin siis pileti teksti kuid vastatud küsimusi ma ära ei kaotaks siiski vaid liigutaks kõige viimasteks.

**Comment by JTerasmaa** [comment]
Punktid juba ongi nummerdatud ;-)
