### ISSUE TITLE
Lisainfo kast, mis saadetakse pärast mängu e-mailiga

### ISSUE THREAD

**Issue by JTerasmaa** [Avastusrada/Avastusrada#41]
Raja küsimuse koostamise vaates kuvatakse lisatekstikast, mille sisu kuvatakse peale punkti vastamist. Mõeldud avatud vastusega küsimuse korral õige vastuse või kommentaari jaoks või siis lisalugemiseks pärast raja läbimist.

Tekstikasti ei kuvata mängimisel ega kokkuvõtvas e-mailis, kui sinna ei ole eelnevalt raja looja sisu lisanud.

**Comment by JTerasmaa** [comment]
Pärast küsimusele vastamist kuvatakse see lisainfo tekst, aga samas jääb alles ka küsimuse muutmise võimalus? Vähemalt on see kast endiselt redigeeritav, kuni vajutatakse "Edasi". Ka valikvastused on endiselt vajutatavad. 

Rajaloomise režimiis kiri "Lisainfo" on väga lähedal "Salvesta" nupule. Raske pihta saada ja märgata.

**Comment by JTerasmaa** [comment]
Jäi veel selline asi silma, et pärast mängu saadetavas e-kirjas on "Lisa info" lahku kirjutad. Võiks ikka koos olla :)

**Comment by tammets** [comment]
1. Lisainfo kast on koguaeg nähtav koostamise vaates:

<img width="647" alt="screen shot 2017-05-12 at 22 13 03" src="https://cloud.githubusercontent.com/assets/380007/26013267/3b3ec66c-3760-11e7-9342-4e0158b44da8.png">

2. Vastuseid peale lisainfo kasti kuvamist (vastamist) muuta ei saa
