### ISSUE TITLE
Pildivastuse puhul piltide kataloogi loomine

### ISSUE THREAD

**Issue by JTerasmaa** [Avastusrada/Avastusrada#49]
Pildivastustega küsimuse korral CSV faili alla laadides pildid ilmselt kaasa ei tule.

Seega kas ja kuidas raja looja pildid üldse kätte saab? Kui pildiküsimusi on palju, siis oleks hea, kui need oleks kusagil ühes kataloogis koos, aga samas teatud struktuuriga.

Kataloogisüsteem näiteks midagi sellist:
Raja nimi -> Kuu -> konkreetne kuupäev millal mäng toimus 

Kas saab ümber nimetada pildifaili? Ajatempli kohe sinna panna vms?

Paralleelselt võiks muidugi olla ka see, et need samad raportid, mis mängija saab omale meilile, genereeritakse näiteks pdf-idena kusagile kataloogi, millele mängu loojal on samuti ligipääs. Või siis saab raja looja need enda e-postile. Samas see võib veidi tüütuks minna, kui rada väga populaarne on.

Oleks mõneti alternatiiviks CSV-le, millel on oma kasutusvajadus kui vaja analüüsida suuremat hulka andmeid. Selliselt kiire ülevaate saamiseks ja tagasisidestamiseks oleks koondraport koos piltidega päris hea.

**Comment by tammets** [comment]
Nupp "lae alla pildid"
