### ISSUE TITLE
Raja punktile saab määrata raadiuse

### ISSUE THREAD

**Issue by tammets** [Avastusrada/Avastusrada#95]
Eemaldada raja seadetest.

**Comment by JTerasmaa** [comment]
Oot, misasja? Raadius tuleb määrata igal punktil alati eraldi? Äkki on lihtsam (ja kiirem ja mugavam), kui vaikimisi lahendus on raja seadetes - kõikidele sama raadius. Ja siis nendel puntkidel, millel vaja, saab selle punktiinfos nö üle kirjutada ja mingid erisused tekitada. Mulle tundub küll, et ega enamasti sobib ju kõikidele sama väärtus.

**Comment by tammets** [comment]
Ei implementeeri.
